export { default as typeCount } from './typeCount.vue'
export { default as wordChart } from './wordChart.vue'
export { default as funnelChart } from './funnelChart.vue'
export { default as lineChart } from './lineChart.vue'
export { default as liquidChart } from './liquidChart.vue'
